<% require_relative 'libraries/helpers' %>

driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: okta-openvpn-build::default
    attributes:
      okta_openvpn_build:
        packagecloud_token: <%= ENV['PACKAGECLOUD_TOKEN'] || 'test' %>
        publish_artifacts: <%= ENV['TRAVIS_PULL_REQUEST'] == 'false' ? true : false %>
        build_version: <%= OktaOpenvpnBuild::Helpers.version %>
        build_revision: <%= OktaOpenvpnBuild::Helpers.revision %>
        source_url: <%= OktaOpenvpnBuild::Helpers.source_url %>
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir:         /opt/okta-openvpn
